data = [
    {'name': 'Instagram', 'follower_count': 692, 'description': 'Social media platform', 'country': 'United States'},
    {'name': 'Cristiano Ronaldo', 'follower_count': 660, 'description': 'Footballer', 'country': 'Portugal'},
    {'name': 'Lionel Messi', 'follower_count': 506, 'description': 'Footballer', 'country': 'Argentina'},
    {'name': 'Selena Gomez', 'follower_count': 418, 'description': 'Musician and actress', 'country': 'United States'},
    {'name': 'Dwayne Johnson', 'follower_count': 393, 'description': 'Actor and professional wrestler', 'country': 'United States'},
    {'name': 'Kylie Jenner', 'follower_count': 393, 'description': 'Reality TV personality and businesswoman', 'country': 'United States'},
    {'name': 'Ariana Grande', 'follower_count': 376, 'description': 'Musician and actress', 'country': 'United States'},
    {'name': 'Kim Kardashian', 'follower_count': 356, 'description': 'Reality TV personality and businesswoman', 'country': 'United States'},
    {'name': 'Beyoncé', 'follower_count': 310, 'description': 'Musician', 'country': 'United States'},
    {'name': 'Khloé Kardashian', 'follower_count': 302, 'description': 'Reality TV personality', 'country': 'United States'},
    {'name': 'Nike', 'follower_count': 300, 'description': 'Sportswear brand', 'country': 'United States'},
    {'name': 'Justin Bieber', 'follower_count': 294, 'description': 'Musician', 'country': 'Canada'},
    {'name': 'Kendall Jenner', 'follower_count': 286, 'description': 'Reality TV personality and model', 'country': 'United States'},
    {'name': 'Taylor Swift', 'follower_count': 280, 'description': 'Musician', 'country': 'United States'},
    {'name': 'National Geographic', 'follower_count': 278, 'description': 'Magazine', 'country': 'United States'},
    {'name': 'Virat Kohli', 'follower_count': 274, 'description': 'Cricketer', 'country': 'India'},
    {'name': 'Jennifer Lopez', 'follower_count': 247, 'description': 'Musician and actress', 'country': 'United States'},
    {'name': 'Neymar Jr', 'follower_count': 231, 'description': 'Footballer', 'country': 'Brasil'},
    {'name': 'Nicki Minaj', 'follower_count': 224, 'description': 'Musician', 'country': 'Trinidad and Tobago'},
    {'name': 'Kourtney Kardashian', 'follower_count': 218, 'description': 'Reality TV personality', 'country': 'United States'},
    {'name': 'Miley Cyrus', 'follower_count': 212, 'description': 'Musician and actress', 'country': 'United States'},
    {'name': 'Katy Perry', 'follower_count': 204, 'description': 'Musician', 'country': 'United States'},
    {'name': 'Zendaya', 'follower_count': 179, 'description': 'Actress and musician', 'country': 'United States'},
    {'name': 'Kevin Hart', 'follower_count': 177, 'description': 'Comedian and actor', 'country': 'United States'},
    {'name': 'Real Madrid CF', 'follower_count': 173, 'description': 'Football club', 'country': 'Spain'},
    {'name': 'Cardi B', 'follower_count': 163, 'description': 'Musician', 'country': 'United States'},
    {'name': 'LeBron James', 'follower_count': 159, 'description': 'Basketball player', 'country': 'United States'},
    {'name': 'Demi Lovato', 'follower_count': 153, 'description': 'Musician and actress', 'country': 'United States'},
    {'name': 'Rihanna', 'follower_count': 149, 'description': 'Musician and businesswoman', 'country': 'Barbados'},
    {'name': 'Chris Brown', 'follower_count': 144, 'description': 'Musician', 'country': 'United States'},
    {'name': 'Drake', 'follower_count': 142, 'description': 'Musician and rapper', 'country': 'Canada'},
    {'name': 'FC Barcelona', 'follower_count': 137, 'description': 'Football club', 'country': 'Spain'},
    {'name': 'Ellen DeGeneres', 'follower_count': 136, 'description': 'Comedian and TV personality', 'country': 'United States'},
    {'name': 'Billie Eilish', 'follower_count': 124, 'description': 'Musician', 'country': 'United States'},
    {'name': 'UEFA Champions League', 'follower_count': 120, 'description': 'Club football competition', 'country': 'Europe'},
    {'name': 'Gal Gadot', 'follower_count': 108, 'description': 'Actress and model', 'country': 'Israel'},
    {'name': 'Lalisa Manoban', 'follower_count': 106, 'description': 'Musician and dancer', 'country': 'Thailand'},
    {'name': 'Vin Diesel', 'follower_count': 103, 'description': 'Actor', 'country': 'United States'},
    {'name': 'NASA', 'follower_count': 96, 'description': 'Space agency', 'country': 'United States'},
    {'name': 'Narendra Modi', 'follower_count': 96, 'description': 'Prime Minister', 'country': 'India'},
    {'name': 'Shakira', 'follower_count': 91, 'description': 'Musician', 'country': 'Colombia'},
    {'name': 'Priyanka Chopra', 'follower_count': 92, 'description': 'Actress and musician', 'country': 'India'},
    {'name': 'NBA', 'follower_count': 90, 'description': 'Basketball Association', 'country': 'United States'},
    {'name': 'Snoop Dogg', 'follower_count': 88, 'description': 'Musician', 'country': 'United States'},
    {'name': 'David Beckham', 'follower_count': 88, 'description': 'Former footballer', 'country': 'United Kingdom'},
    {'name': 'Dua Lipa', 'follower_count': 87, 'description': 'Musician', 'country': 'United Kingdom'},
    {'name': 'Kim Jennie', 'follower_count': 87, 'description': 'Musician and actress', 'country': 'South Korea'},
    {'name': 'Alia Bhatt', 'follower_count': 86, 'description': 'Actress and musician', 'country': 'India'},
]
